name: build
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Build
        run: |
          nix run '.#build'

      - name: Upload Cheatsheets
        uses: actions/upload-artifact@v4
        with:
          name: cheatsheets
          path: build/*.pdf
